### ISSUE TITLE
No LuaRocks module found for fb.torch.async_rng

### ISSUE THREAD

**Issue by dhiren1992** [facebook/fbcunn#106]
I have followed instructions in [INSTALL.md](https://github.com/facebook/fbcunn/blob/master/INSTALL.md) by @soumith and was able to install torch locally then I use https://github.com/facebook/fblualib/blob/master/install_all.sh to install Folly, fbthrift, thpp and fblualib. As I was running into trouble similar to [issue 11 from thpp](https://github.com/facebook/thpp/issues/11) and the continued to install fbcunn. After wich i require fbnn and fbcunn in torch and it troughs error No LuaRocks module found for fb.torch.async_rng

th> require 'fbnn'
/home/dime/torch/install/share/lua/5.1/trepl/init.lua:384: /home/dime/torch/install/share/lua/5.1/trepl/init.lua:384: module 'fb.torch.async_rng' not found:No LuaRocks module found for fb.torch.async_rng
    no field package.preload['fb.torch.async_rng']
    no file '/home/dime/.luarocks/share/lua/5.1/fb/torch/async_rng.lua'
    no file '/home/dime/.luarocks/share/lua/5.1/fb/torch/async_rng/init.lua'
    no file '/home/dime/torch/install/share/lua/5.1/fb/torch/async_rng.lua'
    no file '/home/dime/torch/install/share/lua/5.1/fb/torch/async_rng/init.lua'
    no file './fb/torch/async_rng.lua'
    no file '/home/dime/torch/install/share/luajit-2.1.0-beta1/fb/torch/async_rng.lua'
    no file '/usr/local/share/lua/5.1/fb/torch/async_rng.lua'
    no file '/usr/local/share/lua/5.1/fb/torch/async_rng/init.lua'
    no file '/home/dime/.luarocks/lib/lua/5.1/fb/torch/async_rng.so'
    no file '/home/dime/torch/install/lib/lua/5.1/fb/torch/async_rng.so'
    no file '/home/dime/torch/install/lib/fb/torch/async_rng.so'
    no file './fb/torch/async_rng.so'
    no file '/usr/local/lib/lua/5.1/fb/torch/async_rng.so'
    no file '/usr/local/lib/lua/5.1/loadall.so'
    no file '/home/dime/.luarocks/lib/lua/5.1/fb.so'
    no file '/home/dime/torch/install/lib/lua/5.1/fb.so'
    no file '/home/dime/torch/install/lib/fb.so'
    no file './fb.so'
    no file '/usr/local/lib/lua/5.1/fb.so'
    no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
    [C]: in function 'error'
    /home/dime/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
    [string "_RESULT={require 'fbnn'}"]:1: in main chunk
    [C]: in function 'xpcall'
    /home/dime/torch/install/share/lua/5.1/trepl/init.lua:651: in function 'repl'
    ...dime/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
    [C]: at 0x00406670    
                                                                      [0.0817s]    
th> fb 'fbcnn'
[string "_RESULT={fb 'fbcnn'}"]:1: attempt to call global 'fb' (a nil value)
stack traceback:
    [string "_RESULT={fb 'fbcnn'}"]:1: in main chunk
    [C]: in function 'xpcall'
    /home/dime/torch/install/share/lua/5.1/trepl/init.lua:651: in function 'repl'
    ...dime/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
    [C]: at 0x00406670    
                                                                      [0.0002s]    
th>
I am not sure how to debug this further. 
FYI I did have to install totem, nngraph and graph during fbtorch installation due to missing dependencies.

**Comment by kvrd18** [comment]
Facing same issue here. Please help.

**Comment by kvrd18** [comment]
I tried installing 'fb.torch' from fblualib to enable the module 'fb.torch.async_rng' and got the following error when I ran luarocks make rocks/fb_torch-0.1-1.rockspec

`In file included from /home/predible/torch/lib/fblualib/fblualib/torch/../../fblualib/LuaUtils.h:264:0,
                 from /home/predible/torch/lib/fblualib/fblualib/torch/AsyncRNG.cpp:11:
/home/predible/torch/lib/fblualib/fblualib/torch/../../fblualib/LuaUtils-inl.h: In instantiation of ‘void fblualib::luaPushTensor(lua_State*, const thpp::Tensor<T>&) [with NT = float; lua_State = lua_State]’:
/home/predible/torch/lib/fblualib/fblualib/torch/AsyncRNG.cpp:165:30:   required from ‘int {anonymous}::AsyncRNG<T>::pushBatch(lua_State*, size_t) [with T = float; lua_State = lua_State; size_t = long unsigned int]’
/home/predible/torch/lib/fblualib/fblualib/torch/AsyncRNG.cpp:544:1:   required from here
/home/predible/torch/lib/fblualib/fblualib/torch/../../fblualib/LuaUtils-inl.h:128:39: error: ‘const class thpp::Tensor<float>’ has no member named ‘copyPtr’
   luaPushTensor<T>(L, tensor.copyPtr());
                                       ^
make[2]: *** [CMakeFiles/async_rng.dir/AsyncRNG.cpp.o] Error 1
make[1]: *** [CMakeFiles/async_rng.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.`

**Comment by dhroiden** [comment]
I think this issue is related to [instaltion bug](https://github.com/facebook/fbcunn/issues/99), as i had to use an alternate link to install torch and fblualib..

**Comment by kvrd18** [comment]
Can you post the alternate links over here?

**Comment by abhishekkrthakur** [comment]
Im facing the same issue. were you able to solve it @dhiren-rachamallu  ?

**Comment by soumith** [comment]
@abhishekkrthakur fbcunn does have a compile error right now. @ebetica is working on fixing it.
What's the reason you are trying to use the fb* stack, i might point you to an alternative.

**Comment by abhishekkrthakur** [comment]
@soumith I'm trying to use NAMAS. I think fbcunn isnt required for that. but I'm also facing errors while importing fbnn : `module 'fb.torch.async_rng' not found:No LuaRocks module found for fb.torch.async_rng`

**Comment by soumith** [comment]
oh i see. cc: @ebetica track and make sure NAMAS works. @abhishekkrthakur he should be fixing this once and for all this week. wrt fb.torc.async_rng , he'll look into that too.

**Comment by jeiranj** [comment]
I am having the same issue, trying to run NAMAS and get the same error with not being able to find  fb.torch.async_rng.  All the install and build steps, including torch, folly, thrift, thpp, fblualib, fbcunn, as outlined here (https://github.com/facebook/fbcunn/blob/master/INSTALL.md) with some modifications* went well with no issues.  Seems like part of the problem is in the fact that the version of `fblualib` that I checked out (see below) has no `fblualib/torch/rockspec/`.  Why is that?

*modifications: I just changed 
`curl -sk https://raw.githubusercontent.com/soumith/fblualib/master/install_all.sh | bash -e`
to 
`curl -sk https://raw.githubusercontent.com/facebook/fblualib/master/install_all.sh | bash -e`
as soumith's version was causing problems with thpp installation.  In short, in the facebook version of `install_all.sh`, these are the versions of repos that are checked out:
```
    git clone -b v0.35.0  --depth 1 https://github.com/facebook/folly
    git clone -b v0.24.0  --depth 1 https://github.com/facebook/fbthrift
    git clone -b v1.0 https://github.com/facebook/thpp
    git clone -b v1.0 https://github.com/facebook/fblualib

```
Now, I noticed that the v1.0 version of `fblualib` has `fblualib/fblualib/torch` but there is no rockspec in it, which is the problem. That is, `fb.torch` has been build but cannot be loaded in torch (try `luajit -e "require('fb.trepl').repl()"` and `luajit -e "require('fb.torch').repl()"` to see the difference).  If you try to build `fblualib` from this other version of the repo `git clone https://github.com/facebook/fblualib` (different than version 1.0), there exists rockspec under `fblualib/fblualib/torch` but you get these errors (some problem with the version of thpp I think):

```
me@mymachine:/tmp/fblualib-build.4tf1Ac/fblualib/fblualib$ ./build.sh
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Folly: /usr/local/include  
-- Found Glog: /usr/include  
-- Found Torch7 in /home/ubuntu/torch/install
-- Found Folly: /usr/local/include  
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/fblualib-build.4tf1Ac/fblualib/fblualib/build
Scanning dependencies of target fblualib
[ 25%] Building CXX object CMakeFiles/fblualib.dir/LuaUtils.cpp.o
In file included from /tmp/fblualib-build.4tf1Ac/fblualib/fblualib/LuaUtils.cpp:11:0:
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils.h:99:40: error: ‘thpp::TensorPtr’ has not been declared
 void luaPushTensor(lua_State* L, thpp::TensorPtr<thpp::Tensor<NT>> tensor);
                                        ^
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils.h:99:49: error: expected ‘,’ or ‘...’ before ‘<’ token
 void luaPushTensor(lua_State* L, thpp::TensorPtr<thpp::Tensor<NT>> tensor);
                                                 ^
In file included from /tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils.h:264:0,
                 from /tmp/fblualib-build.4tf1Ac/fblualib/fblualib/LuaUtils.cpp:11:
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils-inl.h:122:40: error: ‘thpp::TensorPtr’ has not been declared
 void luaPushTensor(lua_State* L, thpp::TensorPtr<thpp::Tensor<T>> tensor) {
                                        ^
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils-inl.h:122:49: error: expected ‘,’ or ‘...’ before ‘<’ token
 void luaPushTensor(lua_State* L, thpp::TensorPtr<thpp::Tensor<T>> tensor) {
                                                 ^
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils-inl.h: In function ‘void fblualib::luaPushTensor(lua_State*, int)’:
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils-inl.h:123:21: error: ‘tensor’ was not declared in this scope
   luaT_pushudata(L, tensor.moveAsTH(), thpp::Tensor<T>::kLuaTypeName);
                     ^
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils-inl.h: At global scope:
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils-inl.h:263:6: error: ‘IsTensorPtr’ is not a member of ‘thpp’
     (thpp::IsTensorPtr<T>::value || thpp::IsStorage<T>::value)>::type>
      ^
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils-inl.h:263:26: error: ‘::value’ has not been declared
     (thpp::IsTensorPtr<T>::value || thpp::IsStorage<T>::value)>::type>
                          ^
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils-inl.h:263:37: error: ‘IsStorage’ is not a member of ‘thpp’
     (thpp::IsTensorPtr<T>::value || thpp::IsStorage<T>::value)>::type>
                                     ^
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils-inl.h:263:55: error: ‘::value’ has not been declared
     (thpp::IsTensorPtr<T>::value || thpp::IsStorage<T>::value)>::type>
                                                       ^
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils-inl.h:263:63: error: template argument 1 is invalid
     (thpp::IsTensorPtr<T>::value || thpp::IsStorage<T>::value)>::type>
                                                               ^
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils-inl.h:263:70: error: expected ‘(’ before ‘>’ token
     (thpp::IsTensorPtr<T>::value || thpp::IsStorage<T>::value)>::type>
                                                                      ^
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils-inl.h:263:70: error: template argument 2 is invalid
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils-inl.h:264:3: error: expected ‘::’ before ‘:’ token
   : public LuaOpBase<T, LuaOp<T>> {
   ^
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils-inl.h:264:3: error: expected identifier before ‘:’ token
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils-inl.h:264:3: error: qualified name does not name a class before ‘:’ token
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils-inl.h:264:3: error: expected ‘{’ before ‘:’ token
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils-inl.h:264:3: error: expected unqualified-id before ‘:’ token
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils-inl.h:282:27: error: ‘IsTensor’ is not a member of ‘thpp’
   typename std::enable_if<thpp::IsTensor<T>::value>::type>
                           ^
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils-inl.h:282:27: error: ‘IsTensor’ is not a member of ‘thpp’
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils-inl.h:282:43: error: template argument 1 is invalid
   typename std::enable_if<thpp::IsTensor<T>::value>::type>
                                           ^
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils-inl.h:282:51: error: expected ‘(’ before ‘>’ token
   typename std::enable_if<thpp::IsTensor<T>::value>::type>
                                                   ^
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils-inl.h:282:51: error: template argument 2 is invalid
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils-inl.h:282:54: error: expected ‘{’ or ‘:’ before ‘type’
   typename std::enable_if<thpp::IsTensor<T>::value>::type>
                                                      ^
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils-inl.h:282:54: error: expected ‘{’ before ‘type’
/tmp/fblualib-build.4tf1Ac/fblualib/fblualib/../fblualib/LuaUtils-inl.h:282:58: error: expected initializer before ‘>’ token
   typename std::enable_if<thpp::IsTensor<T>::value>::type>
                                                          ^
make[2]: *** [CMakeFiles/fblualib.dir/LuaUtils.cpp.o] Error 1
make[1]: *** [CMakeFiles/fblualib.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by jeiranj** [comment]
By the way, the same issue exist with `fb.python` too.  It cannot be loaded in torch either, just like `fb.torch`.  `rockspec` exits in `fblualib/pyhon`!!  What is happening?!

**Comment by kvrd18** [comment]
Any updates on this?

**Comment by ebetica** [comment]
Try this PR: https://github.com/facebook/fblualib/pull/70 it should fix the AsynRNG issue. Unfortunately I didn't get to test it on a old system like Ubuntu, but I got FBCUNN to build on master...

**Comment by jeiranj** [comment]
One question, seems like the `install_all` script has not been updated to clone the most recent versions of fblualib. 
`git clone -b v1.0 https://github.com/facebook/fblualib`  should be replaced with `git clone https://github.com/facebook/fblualib`; correct?

**Comment by jeiranj** [comment]
I still get an error when building fblualib (the last step in install_all):

```
...
Scanning dependencies of target fblualib
[ 25%] Building CXX object CMakeFiles/fblualib.dir/LuaUtils.cpp.o
c++: error: unrecognized command line option ‘-std=gnu++14’
make[2]: *** [CMakeFiles/fblualib.dir/LuaUtils.cpp.o] Error 1
make[1]: *** [CMakeFiles/fblualib.dir/all] Error 2
make: *** [all] Error 2
```
:'-(

**Comment by ebetica** [comment]
http://stackoverflow.com/questions/31965413/compile-c14-code-with-g

It looks like you need to use gnu++1y instead, since folly changed to c++14 on their master branch. Can you test it by modifying the cmake files?

**Comment by jeiranj** [comment]
I will try to modify the cmake files, but I may be able to upgrade.  But my other question was about which `install_all` should be used.  Soumith's version or Facebook's?
https://raw.githubusercontent.com/soumith/fblualib/master/install_all.sh  or https://raw.githubusercontent.com/facebook/fblualib/master/install_all.sh?
The cloned thpp and fblualib versions are different.

**Comment by ebetica** [comment]
I don't have a good answer for that, because I don't have access to an older version of Ubuntu to test on. I confirmed that cloning the master branch of each repo definitely built on GCC 5.4 and GCC 6.1. I'll work on setting up a VM to test a fresh build on Ubuntu 16 when I get the chance, and update the install_all then.

**Comment by jeiranj** [comment]
Thanks a ton.  I'm waiting...

**Comment by kvrd18** [comment]
@jeiranj Were you able to install thpp using the versions you posted in your comment?

**Comment by jeiranj** [comment]
not yet.  I am testing things with ubuntu16 now, but there is some cuda issues which I have to yet solve.

**Comment by ixaxaar** [comment]
Tried to compile fblualib master after modifying the `gnu++` option with `c++1y` on ubuntu `14.04`

```bash
sed -i "s/gnu++14/c++1y/" build/CMakeFiles/fblualib.dir/flags.make
sed -i "s/gnu++14/c++1y/" thrift/CMakeLists.txt
sed -i "s/gnu++14/c++1y/" CMakeLists.txt
sed -i "s/gnu++14/c++1y/" util/CMakeLists.txt
sed -i "s/gnu++14/c++1y/" build/CMakeFiles/fblualib.dir/link.txt
```

failed to compile with
```bash
In file included from /home/ubuntu/fblualib/fblualib/LuaUtils.cpp:11:0:
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils.h:99:40: error: 'thpp::TensorPtr' has not been declared
 void luaPushTensor(lua_State* L, thpp::TensorPtr<thpp::Tensor<NT>> tensor);
                                        ^
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils.h:99:49: error: expected ',' or '...' before '<' token
 void luaPushTensor(lua_State* L, thpp::TensorPtr<thpp::Tensor<NT>> tensor);
                                                 ^
In file included from /home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils.h:264:0,
                 from /home/ubuntu/fblualib/fblualib/LuaUtils.cpp:11:
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils-inl.h:122:40: error: 'thpp::TensorPtr' has not been declared
 void luaPushTensor(lua_State* L, thpp::TensorPtr<thpp::Tensor<T>> tensor) {
                                        ^
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils-inl.h:122:49: error: expected ',' or '...' before '<' token
 void luaPushTensor(lua_State* L, thpp::TensorPtr<thpp::Tensor<T>> tensor) {
                                                 ^
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils-inl.h: In function 'void fblualib::luaPushTensor(lua_State*, int)':
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils-inl.h:123:21: error: 'tensor' was not declared in this scope
   luaT_pushudata(L, tensor.moveAsTH(), thpp::Tensor<T>::kLuaTypeName);
                     ^
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils-inl.h: At global scope:
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils-inl.h:263:6: error: 'IsTensorPtr' is not a member of 'thpp'
     (thpp::IsTensorPtr<T>::value || thpp::IsStorage<T>::value)>::type>
      ^
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils-inl.h:263:26: error: '::value' has not been declared
     (thpp::IsTensorPtr<T>::value || thpp::IsStorage<T>::value)>::type>
                          ^
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils-inl.h:263:37: error: 'IsStorage' is not a member of 'thpp'
     (thpp::IsTensorPtr<T>::value || thpp::IsStorage<T>::value)>::type>
                                     ^
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils-inl.h:263:55: error: '::value' has not been declared
     (thpp::IsTensorPtr<T>::value || thpp::IsStorage<T>::value)>::type>
                                                       ^
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils-inl.h:263:63: error: template argument 1 is invalid
     (thpp::IsTensorPtr<T>::value || thpp::IsStorage<T>::value)>::type>
                                                               ^
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils-inl.h:263:70: error: expected '(' before '>' token
     (thpp::IsTensorPtr<T>::value || thpp::IsStorage<T>::value)>::type>
                                                                      ^
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils-inl.h:263:70: error: template argument 2 is invalid
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils-inl.h:264:3: error: expected '::' before ':' token
   : public LuaOpBase<T, LuaOp<T>> {
   ^
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils-inl.h:264:3: error: expected identifier before ':' token
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils-inl.h:264:3: error: qualified name does not name a class before ':' token
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils-inl.h:264:3: error: expected '{' before ':' token
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils-inl.h:264:3: error: expected unqualified-id before ':' token
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils-inl.h:282:27: error: 'IsTensor' is not a member of 'thpp'
   typename std::enable_if<thpp::IsTensor<T>::value>::type>
                           ^
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils-inl.h:282:27: error: 'IsTensor' is not a member of 'thpp'
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils-inl.h:282:43: error: template argument 1 is invalid
   typename std::enable_if<thpp::IsTensor<T>::value>::type>
                                           ^
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils-inl.h:282:51: error: expected '(' before '>' token
   typename std::enable_if<thpp::IsTensor<T>::value>::type>
                                                   ^
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils-inl.h:282:51: error: template argument 2 is invalid
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils-inl.h:282:54: error: expected '{' or ':' before 'type'
   typename std::enable_if<thpp::IsTensor<T>::value>::type>
                                                      ^
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils-inl.h:282:54: error: expected '{' before 'type'
/home/ubuntu/fblualib/fblualib/../fblualib/LuaUtils-inl.h:282:58: error: expected initializer before '>' token
   typename std::enable_if<thpp::IsTensor<T>::value>::type>
                                                          ^
make[2]: *** [CMakeFiles/fblualib.dir/LuaUtils.cpp.o] Error 1
make[1]: *** [CMakeFiles/fblualib.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ixaxaar** [comment]
okay so I basically did this:

```
git clone https://github.com/facebook/fblualib.git
git clone https://github.com/facebook/fblualib.git fblualib2

cd fblualib/fblualib
git checkout v1.0
mv torch torch2
mv ../../fblualib2/fblualib/torch/rockspec .
```

then edit `build.sh` to add `torch` to the end of this command:
```bash
rocks="util luaunit complex \
  ffivector editline trepl debugger mattorch python thrift torch"
version='0.1-1'
for rock in $rocks; do
  cd $root/$rock
  # Unfortunately, luarocks doesn't like separating the "build" and
  # "install" phases, so we have to run as root.
  sudo luarocks make rockspec/*.rockspec
done
```

and then 
```c
echo '
extern "C" int luaopen_fb_torch_async_rng(lua_State* L) {
  LUAOPEN(L);
}
' >> ./AsyncRNG.cpp
```

and `./build.sh` worked and so does NAMAS :grimacing:

**Comment by jasclark** [comment]
@ixaxaar, I'm trying to duplicate what you've done, but the torch rock wont build without a torch folder.  You've moved torch to torch2. Am I missing something?

**Comment by SilunWang** [comment]
@ixaxaar is right. You need to utilize:

1. 
`AsyncRNG.cpp` v1.0 (appending:
`extern "C" int luaopen_fb_torch_async_rng(lua_State* L) {
  LUAOPEN(L);
}` to the end of it. )
2. 
`rockspec`, `CMakeLists.txt` in current version

Now running NAMAS smoothly. Thanks a lot!

**Comment by SilunWang** [comment]
@jasclark try this:

```
git clone https://github.com/facebook/fblualib.git
git clone https://github.com/facebook/fblualib.git fblualib2

cd fblualib/fblualib
git checkout v1.0
cd torch
mv ../../fblualib2/fblualib/torch/rockspec .
mv ../../fblualib2/fblualib/torch/CMakeLists.txt .
cd ..
```
then edit `build.sh` and then
```
cd torch
echo '
extern "C" int luaopen_fb_torch_async_rng(lua_State* L) {
  LUAOPEN(L);
}
' >> ./AsyncRNG.cpp
```

**Comment by jasclark** [comment]
@SilunWang, thanks for the help.  After following your suggestions, build.sh failed with 

`Error: File not found: rockspec/fbtorch-0.1-1.rockspec`

Turns out the rockspec filename starts with fb_torch, not fbtorch.  I modified build.sh to install torch with the correct rockspec name.  This allows build.sh to finish without errors.  However, when I try to require fbcunn I now get the following error:

`/home/ubuntu/torch/install/share/lua/5.1/trepl/init.lua:384: ...orch/install/share/lua/5.1/fbcunn/BatchNormalization.lua:69: /home/ubuntu/torch/install/lib/lua/5.1/torch_fb_fbcunn_batch_norm.so: undefined symbol: _ZN6google21kLogSiteUninitializedE
stack traceback:
	/home/ubuntu/torch/install/share/lua/5.1/fb/util/error.lua:76: in function </home/ubuntu/torch/install/share/lua/5.1/fb/util/error.lua:72>
	[C]: in function 'error'
	/home/ubuntu/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	[string "_RESULT={require('fbcunn')}"]:1: in main chunk
	[C]: in function 'real_xpcall'
	/home/ubuntu/torch/install/share/lua/5.1/fb/util/error.lua:85: in function 'xpcall'
	/home/ubuntu/torch/install/share/lua/5.1/trepl/init.lua:652: in function 'repl'
	...untu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x00406670`

**Comment by SilunWang** [comment]
@jasclark Never met this error before. Are you using Lua 5.1 instead of LuaJIT for Torch?

Read this: https://github.com/facebook/fblualib/blob/master/INSTALL.md

**Comment by jasclark** [comment]
@SilunWang, No I'm using LuaJit.  I think the problem has been fixed.  I added 'glog' to TARGET_LINK_LIBRARIES in fbcunn's CMakeLists.txt.

I changed this:

`TARGET_LINK_LIBRARIES(torch_fb_fbcunn_batch_norm luaT THC TH thpp folly ${CUDA_LIBRARIES} ${CUDA_CUFFT_LIBRARIES} ${CUDA_CUBLAS_LIBRARIES})`

to this: 

`TARGET_LINK_LIBRARIES(torch_fb_fbcunn_batch_norm glog luaT THC TH thpp folly ${CUDA_LIBRARIES} ${CUDA_CUFFT_LIBRARIES} ${CUDA_CUBLAS_LIBRARIES})`

I still need to do further testing but I'm cautiously optimistic.  Thanks for your help!

**Comment by ixaxaar** [comment]
Sorry for the delay but you may need to do this in build.sh (refer above):

```
sudo luarocks make rockspec/*.rockspec
```

**Comment by atana1** [comment]
I have the same issue. I tried approach mentioned by @ixaxaar  and @SilunWang and then ran `build.sh` but it throws error as:

dave@home:~/fblualib/fblualib$ ./build.sh 
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Folly: /usr/local/include  
-- Found Glog: /usr/include  
-- Found Torch7 in /home/dave/torch/install
-- REQUIRED_ARGS (missing:  THPP_INCLUDE_DIR THPP_LIBRARIES) 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
THPP_INCLUDE_DIR
   used as include directory in directory /home/dave/fblualib/fblualib
   used as include directory in directory /home/dave/fblualib/fblualib
   used as include directory in directory /home/dave/fblualib/fblualib
   used as include directory in directory /home/dave/fblualib/fblualib
   used as include directory in directory /home/dave/fblualib/fblualib
   used as include directory in directory /home/dave/fblualib/fblualib
   used as include directory in directory /home/dave/fblualib/fblualib
THPP_LIBRARY
    linked by target "fblualib" in directory /home/dave/fblualib/fblualib

-- Configuring incomplete, errors occurred!
See also "/home/dave/fblualib/fblualib/build/CMakeFiles/CMakeOutput.log".
dave@home:~/fblualib/fblualib$ 

Any idea how to fix this ? I am using ubuntu 14.04

**Comment by atana1** [comment]
Hi, I am trying to run NAMAS, and got the same error 'No LuaRocks module found for fb.torch.async_rng' so tried to install fblualib as mentioned by @ixaxaar and @SilunWang. So, before running the build.sh of fblualib I need to install folly, fbthrift, thpp.

I ran install_all.sh from v1.0 of fblualib with v1.0 of thpp
git clone -b v0.35.0  --depth 1 https://github.com/facebook/folly.git
git clone -b v0.24.0  --depth 1 https://github.com/facebook/fbthrift.git
git clone -b v1.0 https://github.com/facebook/thpp
git clone https://github.com/soumith/fblualib

but it throws error while building thpp as:

   creating: googletest-release-1.7.0/xcode/Samples/FrameworkSample/WidgetFramework.xcodeproj/
  inflating: googletest-release-1.7.0/xcode/Samples/FrameworkSample/WidgetFramework.xcodeproj/project.pbxproj  
  inflating: googletest-release-1.7.0/xcode/Samples/FrameworkSample/runtests.sh  
  inflating: googletest-release-1.7.0/xcode/Samples/FrameworkSample/widget.cc  
  inflating: googletest-release-1.7.0/xcode/Samples/FrameworkSample/widget.h  
  inflating: googletest-release-1.7.0/xcode/Samples/FrameworkSample/widget_test.cc  
   creating: googletest-release-1.7.0/xcode/Scripts/
  inflating: googletest-release-1.7.0/xcode/Scripts/runtests.sh  
  inflating: googletest-release-1.7.0/xcode/Scripts/versiongenerate.py  
   creating: googletest-release-1.7.0/xcode/gtest.xcodeproj/
  inflating: googletest-release-1.7.0/xcode/gtest.xcodeproj/project.pbxproj  
-- Found Torch7 in /home/atana/torch/install
-- Configuring done
-- Generating done
-- Build files have been written to: /home/abhishek/thpp/thpp/build
[  5%] Building CXX object CMakeFiles/thpp.dir/Storage.cpp.o
/home/atana/thpp/thpp/Storage.cpp: In function ‘void thpp::detail::applySharingMode(folly::IOBuf&, thpp::SharingMode)’:
/home/abhishek/thpp/thpp/Storage.cpp:70:9: error: ‘class folly::IOBuf’ has no member named ‘makeManagedOne’
     iob.makeManagedOne();
         ^
make[2]: *** [CMakeFiles/thpp.dir/Storage.cpp.o] Error 1
make[1]: *** [CMakeFiles/thpp.dir/all] Error 2
make: *** [all] Error 2

I am Ubuntu 14.04
@ixaxaar , @SilunWang which version did you guys checkout while installing? please help.

**Comment by ixaxaar** [comment]
IDK, did not observe that error, maybe you should raise a new issue?

**Comment by ixaxaar** [comment]
Oh well I ended up setting this thing up again on ubuntu 14.04 on AWS's AMI: `Deep Learning AMI Ubuntu Linux - 1.1 (ami-3568a023)`

This is the script I ended up with:
```bash
#!/usr/bin/env bash

# Install base
sudo apt-get update
sudo apt-get install -y \
    git \
    curl \
    wget \
    g++ \
    automake \
    autoconf \
    autoconf-archive \
    libtool \
    libboost-all-dev \
    libevent-dev \
    libdouble-conversion-dev \
    libgoogle-glog-dev \
    libgflags-dev \
    liblz4-dev \
    liblzma-dev \
    libsnappy-dev \
    make \
    zlib1g-dev \
    binutils-dev \
    libjemalloc-dev \
    $extra_packages \
    flex \
    bison \
    libkrb5-dev \
    libsasl2-dev \
    libnuma-dev \
    pkg-config \
    libssl-dev \
    libedit-dev \
    libmatio-dev \
    libpython-dev \
    libpython3-dev \
    python-numpy

sudo apt-get install -y build-essential
sudo apt-get install -y python-pip
sudo apt-get install -y zsh
sudo sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
sudo chown -R ubuntu:ubuntu ~/.zsh*
sudo chown -R ubuntu:ubuntu ~/.oh-my-zsh
sudo pip install awscli

# Install gcc 4.9 for c++14 support
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install g++-4.9
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 10
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20

sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 10
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20

sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30
sudo update-alternatives --set cc /usr/bin/gcc

sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30
sudo update-alternatives --set c++ /usr/bin/g++


# configure locales
export LC_ALL="en_US.UTF-8"
sudo locale-gen en_US en_US.UTF-8
sudo dpkg-reconfigure locales

# Install torch
git clone https://github.com/torch/distro.git ~/torch --recursive
cd ~/torch
sudo bash install-deps
./install.sh
echo '. /home/ubuntu/src/torch/install/bin/torch-activate' >> ~/.zshrc
echo '. /home/ubuntu/torch/install/bin/torch-activate' >> ~/.zshrc
echo 'alias c=clear' >> ~/.zshrc
echo 'l="ls -lh"' >> ~/.zshrc
source ~/.zshrc
cd ..
sudo chown -R ubuntu:ubuntu ./torch

# Install torch libs
luarocks install hdf5
luarocks install nn
luarocks install nngraph
luarocks install cutorch
luarocks install cunn
luarocks install cudnn
luarocks install luautf8
luarocks install class
luarocks install pprint

# Setup facebook's deep learning stack
git clone --depth 1 https://github.com/facebook/folly
cd folly/folly
autoreconf -ivf
./configure
make
sudo make install
sudo ldconfig
cd ../..

sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
sudo apt-get update
sudo apt-get install -y cmake

git clone https://github.com/no1msd/mstch
cd mstch
mkdir build
cd build
cmake ..
make
sudo make install
cd ../..

git clone https://github.com/facebook/wangle
cd wangle/wangle
cmake .
make
sudo make install
cd ../..

git clone https://github.com/facebook/zstd.git
cd zstd
make
sudo make install
cd ..

git clone --depth 1 https://github.com/facebook/fbthrift
cd fbthrift/thrift
autoreconf -ivf
./configure
sudo make
sudo make install
cd ../..

git clone https://github.com/facebook/thpp
cd thpp/thpp
echo '
diff --git a/thpp/CMakeLists.txt b/thpp/CMakeLists.txt
index 4ae3683..77083cf 100644
--- a/thpp/CMakeLists.txt
+++ b/thpp/CMakeLists.txt
@@ -106,18 +106,6 @@ IF(THRIFT_FOUND)
 ENDIF()


-IF(NOT NO_TESTS)
-  ENABLE_TESTING()
-  FIND_PACKAGE(Glog REQUIRED)
-  INCLUDE_DIRECTORIES(${GLOG_INCLUDE_DIR})
-  TARGET_LINK_LIBRARIES(thpp ${GLOG_LIBRARIES})
-  ADD_SUBDIRECTORY("googletest-release-1.7.0")
-  INCLUDE_DIRECTORIES(
-    "${CMAKE_CURRENT_SOURCE_DIR}/googletest-release-1.7.0/include"
-  )
-  ADD_SUBDIRECTORY("test")
-ENDIF()
-

 # SET(CMAKE_INSTALL_PREFIX ${SAVED_CMAKE_INSTALL_PREFIX})

diff --git a/thpp/build.sh b/thpp/build.sh
index 79af5d9..4e949c4 100755
--- a/thpp/build.sh
+++ b/thpp/build.sh
@@ -49,7 +49,6 @@ cmake $FB ..
 make

 # Run tests
-ctest

 # Install
 make install
' > thpp.patch
git apply ./thpp.patch
find ./ -type f -exec sed -i -e 's/\-std=gnu++11/\-std=gnu++14/g' {} \;
./build.sh
cd ../..

git clone https://github.com/facebook/fblualib
cd fblualib/fblualib
# ./build.sh
cmake -D THPP_LIBRARY:STRING=/home/ubuntu/torch/install/lib/libthpp.so -DTHPP_INCLUDE_DIR:STRING=/home/ubuntu/torch/install/include/ .
make
sudo make install

rocks="util luaunit complex \
  ffivector editline trepl debugger mattorch python thrift torch"
version='0.1-1'
for rock in $rocks; do
  cd ./$rock
  echo $rock
  # Unfortunately, luarocks doesn't like separating the "build" and
  # "install" phases, so we have to run as root.
  luarocks make ./rockspec/*.rockspec
  cd ..
done
cd ../..

git clone https://github.com/facebook/fbnn.git && cd fbnn
luarocks make rocks/fbnn-scm-1.rockspec
cd ..

git clone https://github.com/facebookarchive/NAMAS.git
export ABS=$PWD
cd NAMAS
th summary/train.lua -help
```

Hope this helps!
